name: LNLN
channels:
  - nvidia
  - pytorch
  - pyg
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - blas=1.0=mkl
  - brotlicffi=1.2.0.0=py311h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=py311h06a4308_0
  - cffi=2.0.0=py311h4eded50_1
  - charset-normalizer=3.4.4=py311h06a4308_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.3=h7354ed3_4
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.20.0=py311h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.2=py311ha78e65c_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py311h06a4308_0
  - jinja2=3.1.6=py311h06a4308_0
  - joblib=1.5.2=py311h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libavif=1.3.0=h3539ee5_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=h27cfd23_1
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtasn1=4.20.0=ha30cf84_0
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.1=h029b1ac_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - mkl-service=2.5.2=py311hacdc0fc_0
  - mkl_fft=2.1.1=py311h8fe796d_0
  - mkl_random=1.3.0=py311h505adc9_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.6.1=py311h06a4308_0
  - numpy=2.3.5=py311h08c6c3d_0
  - numpy-base=2.3.5=py311h00548fb_0
  - ocl-icd=2.3.3=h47b2149_0
  - opencl-headers=2025.07.22=hfb20e49_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=3.0.18=hd6dcaed_0
  - pcre2=10.46=hf426167_0
  - pillow=12.0.0=py311h3b88751_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_1
  - python=3.11.7=h955ad1f_0
  - pytorch=2.3.1=py3.11_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py311h591646f_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py311h06a4308_1
  - scikit-learn=1.8.0=py311h86c3e14_0
  - scipy=1.16.3=py311h33bc11c_0
  - setuptools=80.9.0=py311h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - sympy=1.14.0=py311h06a4308_1
  - tbb-devel=2022.3.0=h698db13_0
  - tesseract=5.2.0=hb0d2e87_3
  - threadpoolctl=3.5.0=py311h7040dfc_1
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=2.3.1=py311_cu121
  - torchtriton=2.3.1=py311
  - torchvision=0.18.1=py311_cu121
  - typing_extensions=4.15.0=py311h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.6.1=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - einops==0.8.1
      - fsspec==2025.12.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - intel-cmplr-lib-ur==2024.2.1
      - intel-openmp==2024.2.1
      - mkl==2024.0.0
      - onemkl-license==2025.3.0
      - packaging==25.0
      - regex==2025.11.3
      - safetensors==0.7.0
      - tbb==2021.13.1
      - tcmlib==1.4.1
      - tokenizers==0.20.3
      - tqdm==4.67.1
      - transformers==4.46.3
      - umf==1.0.2
